# Generated by Django 4.2.8 on 2024-01-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='PID',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
