version: '3.8'

services:
  backend:
    image: backend-django:latest
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=django_testing
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=mysql
      - DB_PORT=3306
    volumes:
      - ./media:/app/media
    restart: always

  mysql:
    image: mysql:latest
    networks:
      - mynetwork
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django_testing
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    restart: always

networks:
  mynetwork:
    driver: bridge
