version: '3.8'

services:
  backend:
    image: backend-django:latest
    ports:
      - "8002:8002"
    depends_on:
      - mysql
    networks:
      - mynetwork
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=django_testing
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=mysql
      - DB_PORT=3306
      - FRONTEND_URL=http://13.201.200.102:3000
      - RAZORPAY_API_KEY = rzp_test_6gVqKVhbGkiCBm
      - RAZORPAY_API_SECRET = C5h0RBvbRPA9sfV1Va0nMnMa
      - EMAIL_HOST_USER = relevent820@gmail.com
      - EMAIL_HOST_PASSWORD = vlqo yshw qruv mthl
    volumes:
      - ./media:/app/media
    restart: always

  mysql:
    image: mysql:latest
    networks:
      - mynetwork
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=django_testing
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    restart: always

networks:
  mynetwork:
    driver: bridge
