# Generated by Django 4.2.8 on 2024-01-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='TID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
