# Generated by Django 4.2.8 on 2024-01-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='order_id',
            field=models.CharField(default='temp', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='TID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
