# Generated by Django 4.2.8 on 2024-02-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_order_id_alter_ticket_tid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(default='not_paid', max_length=20),
        ),
    ]
