# Generated by Django 4.2.8 on 2023-12-20 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("EID", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=255)),
                ("startDate", models.DateField()),
                ("endDate", models.DateField()),
                ("location", models.CharField(max_length=255)),
                ("latitude", models.DecimalField(decimal_places=10, max_digits=13)),
                ("longitude", models.DecimalField(decimal_places=10, max_digits=13)),
                ("time", models.TimeField()),
                ("require_volunteers", models.BooleanField(default=False)),
                (
                    "poster",
                    models.ImageField(
                        blank=True, null=True, upload_to="event_posters/"
                    ),
                ),
                ("ticket_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=510, null=True)),
                (
                    "medium",
                    models.CharField(
                        choices=[("offline", "Offline"), ("online", "Online")],
                        default="offline",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music", "Music"),
                            ("games", "Games"),
                            ("sports", "Sports"),
                            ("arts", "Arts"),
                            ("film", "Film"),
                            ("literature", "Literature"),
                            ("technology", "Technology"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(decimal_places=2, max_digits=2, null=True),
                ),
                ("privacy", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
