# Generated by Django 5.0 on 2023-12-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_require_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('games', 'Games'), ('sports', 'Sports'), ('arts', 'Arts'), ('film', 'Film'), ('literature', 'Literature'), ('technology', 'Technology'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='medium',
            field=models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], default='offline', max_length=10),
        ),
    ]
